[WIP]add  dynabert
PaddlePaddle/PaddleSlim pull request #1065
Opened 2022-04-22 11:18 UTC by ceci3

add dynabert

2022-04-27 11:57 UTC, yghstill approved these changes, later dismissed

2022-04-28 03:56 UTC, qingqing01 requested changes

2022-04-28 03:56 UTC, qingqing01 commented on paddleslim/auto_compression/create_compressed_program.py
> +            pruned_program = pruner_transformer(
可以封装一个通用的 TransformerUnstructuredPruner ，和其他的保持一致~

2022-05-04 06:46 UTC, ceci3 commented on paddleslim/auto_compression/create_compressed_program.py
> +            pruned_program = pruner_transformer(
done

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +def create_strategy_config(strategy_str, model_type):
将组合策略信息存储到string中，太不直观了，建议声明一个class来存储这些信息，或者结合枚举类型来组织，可以达到如下的效果。

strategy = Strategy.SPARSE_0.5_INT8
if strategy.is_sparse == True:
    ratio = strategy.sparse_ratio
strategy.is_quantization == True

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +    ### only quant
这个注释什么意思？哪种情况是only quant?

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +            configs = [{
对于“prune_0.5_int8”，上边“if len(tmp_s) == 3”分支的逻辑是无效的么？这里直接将configs覆盖了。

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +hpo_config_tester = {
这个命名完全看不出什么意思

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +def auto_prepare_strategy(model_dir,
如果该方法所在package命名中已经有auto关键字了，这个方法就不建议再加auto前缀

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +                          params_filename,
和load_inference_model接口保持一致？
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/load_inference_model_cn.html#load-inference-model

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +            model_file, param_file, hardware=deploy_hardware)
这里不用“model_dir”了么？

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +            max_speedup_strategy = -1.0
这命名不合适，数值“-1.0”不是一种strategy

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +                    'sparse_0.75_fp32', 'prune_0.3_fp32', 'origin_int8',
找个变量存储这个list

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +                    max_speedup_strategy = speedup_ratio[s]
怎么避免s not in speedup_ratio的情况呢？如果无法避免，则需要特殊处理下。

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +                    candidate_s.append(pre_s)
如果第一个策略的ratio>target_speedup, 则candidate_s会append一个None，确定不会出问题么？

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +                pre_s = strategy
是找到第一个满足条件的策略，并将其和上一个不满足条件的策略一起放入候选list？

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +                candidate_ratio = sorted(
对candidate_s排序后，变成candidate_ratio了？排序不应该改变集合的类型，命名不合适。

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +                            1]) <= 0.75:
字符串’sparse‘、数字0.75都相当于魔法数字，要用变量来代替。

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +    else:
如果上个if分支代码量很大，可以在这里加个注释，# if deploy_hardware is None

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +            if model_type == 'transformer':
可以把这些特殊的case放到一个全局dict中，方便管理。

2022-05-04 13:06 UTC, wanghaoshuang commented on paddleslim/auto_compression/auto_strategy.py
> +    if ptq_loss <= 0.03:
魔法数字

2022-05-09 04:00 UTC, qingqing01 submitted a review, later dismissed

2022-05-09 07:12 UTC, yghstill approved these changes

2022-05-09 08:02 UTC, merged