add_ppminilm_demo
PaddlePaddle/PaddleSlim pull request #1082
Opened 2022-05-07 10:57 UTC by RachelXu7

demo of PPMiniLM

2022-05-08 16:09 UTC, qingqing01 commented on demo/auto-compression/demo_ppminilm.py
> +import os
统一放到 demo/auto-compression/pp-minilm 文件夹下

2022-05-09 08:33 UTC, ceci3 commented on demo/auto-compression/pp-minilm/README.md
> +- 蒸馏参数
![image](https://user-images.githubusercontent.com/29245900/167370645-b36310dd-eec7-44d6-957d-1bb89fbba1af.png)
这些位置的换行不对

2022-05-09 08:33 UTC, ceci3 commented on demo/auto-compression/pp-minilm/README.md
> +- 剪枝参数
同上

2022-05-09 08:33 UTC, ceci3 commented on demo/auto-compression/pp-minilm/README.md
> +- 训练参数
同上

2022-05-09 08:33 UTC, ceci3 commented on demo/auto-compression/pp-minilm/README.md
> +量化参数主要设置量化比特数和量化op类型，其中量化op包含卷积层（conv2d, depthwise_conv2d）和全连接层（matmul，matmul_v2）。
全连接层这里写的是 matmul，下面写的是mul

2022-05-09 08:33 UTC, ceci3 commented on demo/auto-compression/pp-minilm/README.md
> +
这两个表格整合到一个里面？感觉这个表格出现好几次

2022-05-09 08:36 UTC, RachelXu7 commented on demo/auto-compression/pp-minilm/README.md
> +
开头结尾repeat了一次。那放开头还是结尾还是结尾呢

2022-05-09 11:39 UTC, qingqing01 commented on demo/auto-compression/pp-minilm/configs/afqmc_cfg.yaml
> +TrainConfig:
都在 configs下面， _cfg 后缀可以去掉

2022-05-12 01:39 UTC, yghstill reviewed
auto-compression重命名为auto_compression

2022-05-12 05:39 UTC, qingqing01 commented on demo/auto-compression/pp-minilm/README.md
> +本示例介绍了对PaddleNLP中PP-MiniLM模型进行自动压缩实验的流程和具体代码。此实验首先对模型所有卷积裁剪25%，同时进行蒸馏训练，然后进行离线量化。
最开始出现PP-MiniLM加链接

2022-05-12 05:39 UTC, qingqing01 commented on demo/auto-compression/pp-minilm/run.py
> +    metric = metric_class()
这个metric在eval_function中采用到吧

2022-05-12 05:39 UTC, qingqing01 commented on demo/auto-compression/pp-minilm/run.py
> +from utility import add_arguments, print_arguments
清理上述没用的导入
这个文件夹下没有utility

2022-05-15 03:59 UTC, yghstill approved these changes, later dismissed

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +- PP-MiniLM模型
简要介绍下什么是PP-MiniLM, 并给个链接到详细介绍页。
至少让用户知道这是小型化的BERT结构。

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +此实验首先对模型所有卷积裁剪25%，同时进行蒸馏训练，然后进行离线量化。
是检测attention head吧？不是卷积。

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +此实验首先对模型所有卷积裁剪25%，同时进行蒸馏训练，然后进行离线量化。
"离线量化"后最好加个(Post-training quantization)。

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +本案例默认以CLUE数据进行自动压缩实验，如数据集为非CLUE格式数据，请修改启动文本run.sh中dataset字段。
会自动下载CLUE数据么？可以明确告知用户。

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +### 2.准备需要量化的环境
建议直接给安装命令，并附上PaddlePaddle和PaddleNLP安装页面的链接.

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +### 3.准备待压缩的部署模型
请直接给出部署模型的下载链接

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +蒸馏量化自动压缩示例通过run.py脚本启动，会使用接口paddleslim.auto_compression.AutoCompression对模型进行量化训练。将任务名称、模型类型、数据集名称、压缩参数传入，对模型进行剪枝、蒸馏训练和离线量化。数据集为CLUE，不同任务名称代表不同CLUE上的任务，可选择的任务名称有：afqmc, tnews, iflytek, ocnli, cmnli, c
“量化训练”？不是只有离线量化么？
“不同任务名称代表不同CLUE上的任务”->“不同任务名称代表CLUE上不同的任务”。

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +蒸馏量化自动压缩示例通过run.py脚本启动，会使用接口paddleslim.auto_compression.AutoCompression对模型进行量化训练。将任务名称、模型类型、数据集名称、压缩参数传入，对模型进行剪枝、蒸馏训练和离线量化。数据集为CLUE，不同任务名称代表不同CLUE上的任务，可选择的任务名称有：afqmc, tnews, iflytek, ocnli, cmnli, c
行内代码建议用以下格式：
`paddleslim.auto_compression.AutoCompression`

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +```
1. 请简要概括介绍下`--config_path='./configs/afqmc.yaml' `的作用。
2. 另起一节或给出其它页面的链接，介绍如何修改剪枝或量化的参数配置。
3. 如果完全是自动的剪枝和量化，不支持用户自己设置相关参数，则显式说明，并重点介绍下afqmc.yaml中的训练参数。

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/run.sh
> +python3.7 run.py \
文档中写的`python`, 你这里用的`python3.7`, 建议对齐。

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/run.sh
> +export PYTHONPATH=/workspace/xuxu/PaddleNLP/:$PYTHONPATH
这两行都不需要吧，前提是已经安装好了PaddleSlim和PaddleNLP

2022-05-16 02:58 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +
也给一下PaddleSlim的安装方式和链接？

2022-05-16 02:59 UTC, wanghaoshuang requested changes
建议再完善下

2022-05-16 08:13 UTC, wanghaoshuang approved these changes

2022-05-16 08:13 UTC, wanghaoshuang commented on demo/auto_compression/nlp/README.md
> +### 进行剪枝蒸馏和离线量化自动压缩
建议将该节提前到“压缩配置介绍”之前。

2022-05-16 08:14 UTC, merged