Add quant advanced tutorial
PaddlePaddle/PaddleSlim pull request #634
Opened 2021-01-29 07:16 UTC by baiyfbupt

2021-02-01 02:29 UTC, qingqing01 commented on docs/zh_cn/tutorials/paddleslim_quantization_overview.md
> +- [在线量化](quant_aware_training_tutorial.md)
在这之前，也可以加个量化方法的overview的表格？ 
QAT, PTQ, Emebedding都包含那些， 推荐用那种？

就是概览性的文档， 让用户看到全局信息、推荐类型、对比等。

类似这样个 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/Overview_cn.html  (虽然这个比较简单)

2021-02-01 02:34 UTC, qingqing01 commented on docs/zh_cn/tutorials/paddleslim_quantization_overview.md
> +PaddleSlim主要包含三种量化方法：在线量化、动态离线量化、静态离线量化
这块也把各自的概念介绍下，以及常用的缩写 QAT, PTQ等介绍下

2021-02-01 02:50 UTC, qingqing01 reviewed
另外，静态图，放到@wanghaoshuang 调整结构后的目录里

2021-02-01 02:50 UTC, qingqing01 commented on docs/zh_cn/tutorials/quant_aware_training_tutorial.md
> +在线量化是在模型训练的过程中建模定点量化对模型的影响，通过在模型计算图中插入量化节点实现，详细算法原理请参考：[量化训练]([https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/algo/algo.md#122-%E9%87%8F%E5%8C%96%E8%AE%AD%E7%BB%83](https://github
原理文档最后会去掉，建议这里不加

2021-02-01 02:50 UTC, qingqing01 commented on docs/zh_cn/tutorials/quant_aware_training_tutorial.md
> +| MobileNetV3_large | pact_quant_aware |     78.96%/94.48%     |      77.52%/93.77%      |
最后加下参考文献

2021-02-01 02:50 UTC, qingqing01 commented on docs/zh_cn/tutorials/quant_aware_training_tutorial.md
> +# 在线量化
这篇文章将QAT的方法，汇总到一个文档里。

建议一开始加下导览。 STE-based QAT (这个名字也注意下是否准确),   PACT.

2021-02-02 08:08 UTC, baiyfbupt commented on docs/zh_cn/tutorials/paddleslim_quantization_overview.md
> +- [在线量化](quant_aware_training_tutorial.md)
done

2021-02-02 08:08 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant_aware_training_tutorial.md
> +| MobileNetV3_large | pact_quant_aware |     78.96%/94.48%     |      77.52%/93.77%      |
done, thanks

2021-02-02 08:08 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant_aware_training_tutorial.md
> +在线量化是在模型训练的过程中建模定点量化对模型的影响，通过在模型计算图中插入量化节点实现，详细算法原理请参考：[量化训练]([https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/algo/algo.md#122-%E9%87%8F%E5%8C%96%E8%AE%AD%E7%BB%83](https://github
removed

2021-02-02 08:11 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant_aware_training_tutorial.md
> +# 在线量化
PACT也是STE-based的，这里就不强调这个概念影响读者理解了。称普通在线量化为QAT

2021-02-02 11:39 UTC, wanghaoshuang requested changes

2021-02-02 11:39 UTC, wanghaoshuang commented on docs/zh_cn/tutorials/quant/embedding_quant_tutorial.md
> +Embedding量化仅能减少模型参数的体积，并不能显著提升模型预测速度
加句号。

2021-02-02 11:39 UTC, wanghaoshuang commented on docs/zh_cn/tutorials/quant/embedding_quant_tutorial.md
> +main_program = paddleslim.quant.quant_embedding(main_program, place, config)
你当前文写的是动态图API么？zh_cn/tutorial/static下放的是静态图文档。

2021-02-02 11:39 UTC, wanghaoshuang commented on docs/zh_cn/tutorials/quant/paddleslim_quantization_overview.md
> +|          在线量化 (QAT)          | 动态图：`paddleslim.dygraph.quant.QAT`; 静态图：`paddleslim.quant.quant_aware` | 通过finetune训练将模型量化误差降到最小 | 对量化敏感的场景、模型，例如目标检测、分割, OCR |
paddleslim.dygraph.quant.QAT -> paddleslim.QAT

2021-02-02 11:39 UTC, wanghaoshuang commented on docs/zh_cn/tutorials/quant/paddleslim_quantization_overview.md
> +| Embedding量化（Quant Embedding） |              `paddleslim.quant.quant_embedding`              |       仅量化模型的Embedding参数        |            任何包含Embedding层的模型            |
这个有动态图实现么？

2021-02-02 11:39 UTC, wanghaoshuang commented on docs/zh_cn/tutorials/quant/quant_aware_training_tutorial.md
> +quanter = paddleslim.dygraph.quant.QAT(config=quant_config)
paddleslim.dygraph.quant.QAT -> paddleslim.QAT

2021-02-02 12:02 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant/embedding_quant_tutorial.md
> +Embedding量化仅能减少模型参数的体积，并不能显著提升模型预测速度
done

2021-02-02 12:03 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant/embedding_quant_tutorial.md
> +main_program = paddleslim.quant.quant_embedding(main_program, place, config)
quant_embedding是静态图api, 已放在zh_cn/tutorial/static

2021-02-02 12:04 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant/paddleslim_quantization_overview.md
> +|          在线量化 (QAT)          | 动态图：`paddleslim.dygraph.quant.QAT`; 静态图：`paddleslim.quant.quant_aware` | 通过finetune训练将模型量化误差降到最小 | 对量化敏感的场景、模型，例如目标检测、分割, OCR |
done

2021-02-02 12:07 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant/paddleslim_quantization_overview.md
> +| Embedding量化（Quant Embedding） |              `paddleslim.quant.quant_embedding`              |       仅量化模型的Embedding参数        |            任何包含Embedding层的模型            |
这个没有，embedding量化只在infer时调用，动态图可以在动转静后再做embedding量化，暂时没发现有必要加动态图api

2021-02-02 12:08 UTC, baiyfbupt commented on docs/zh_cn/tutorials/quant/quant_aware_training_tutorial.md
> +quanter = paddleslim.dygraph.quant.QAT(config=quant_config)
done

2021-02-02 12:12 UTC, wanghaoshuang approved these changes

2021-02-03 08:08 UTC, merged