[distill] enhance hook
PaddlePaddle/PaddleSlim pull request #897
Opened 2021-09-17 17:28 UTC by ceci3

support get input in hook
support specific the index of input/output in hook

2021-09-27 15:36 UTC, wanghaoshuang requested changes

2021-09-27 15:36 UTC, wanghaoshuang commented on demo/dygraph/dist/bert/task_distill.py
> +        parameters=distill_model.parameters(),
这里是为了让align操作引入的parameters参与训练？

2021-09-27 15:36 UTC, wanghaoshuang commented on demo/dygraph/dist/bert/task_distill.py
> +    assert os.path.exists(
尽量将蒸馏相关的语句放在一起，然后用注释标出主要步骤。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
>          Distill API.
要说明这个API是做什么的，要让用户看了之后就能猜出来需要设置哪些参数。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
>                   distill_configs,
如果参数列表只有一个config，那就不用加“distill_”前缀了。命名最好和其他repo保持一致。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
>          distill_configs(list(dict) | path): the list of distill config.
说明config的格式，或者给个详细说明的链接。
如果是list(dict), 则list中每个元素代表什么？
path不是类型，改成string, 然后解释如果是该类型，代表什么意思，有什么限制。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
>          student_models(list(nn.Layer)): the list of student model, the state of student model must be training mode.
可以自动的把student的模型设置为training mode吗？

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
> +        teacher_models(list(nn.Layer)): the list of teacher model.
简化为"teachers"和"students"?

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
>          return_model_outputs(bool): whether to return model output. Default: True.
只返回student的outputs吗？如果是的话，改成“return_student_outputs”?
返回内容的格式是什么？如果有多个students，格式是什么？

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
> +                 convert_fn=True,
请添加注释。这个注释挺重要的，一定要写详细点。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill_helpers.py
> +def paddle_convert_fn():
1. 把该方法迁移到paddleslim.common，并暴露paddleslim.paddle_convert_fn;
2. 建议命名更直观些，比如：functional2layer;
3. 添加注释，说明效果和影响范围，最好有示例。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill_helpers.py
> +    print("convert function to class")
remove unused lines

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill_helpers.py
> +            if getattr(model, 'wrap_fn_{}_{}'.format(fn.__name__, global_idx),
加TODO待支持含有if分支的模型。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill_helpers.py
> +                setattr(model, 'wrap_fn_{}_{}'.format(fn.__name__, global_idx),
要不要调用一下[add_sublayer](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Layer_cn.html#add_sublayer)?

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill_helpers.py
> +            setattr(F, 'before_{}'.format(f), eval('F.{}'.format(f)))
before_relu是对relu的备份？“before”不太合适吧？还有“after_”，请再斟酌下。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill_helpers.py
> +            result = eval('F.before_{}'.format(fn.__name__))(*x, **kwargs)
如果在一个Layer中调用了多个functional API呢？是不是也要将其中的所有functional API转成Layer? 或者咱不考虑这种情况，但是要加TODO记录一下。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill_helpers.py
> +class wrapper(nn.Layer):
统一class命名规则, 建议首字母大写。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
> +            paddle_convert_fn()
是不是可以考虑把该操作交给用户去显式调用？在声明Distill实例之前调用。
用户调用该方法之后，可以根据新的layer 名称配置config。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
> +            self._loss_config_list.append(layer_config)
最好是将_loss_config_list return出来，然后再赋值给self._loss_config_list，否则看不出来_transpose_config会修改self._loss_config_list。

2021-09-27 15:36 UTC, wanghaoshuang commented on paddleslim/dygraph/dist/distill.py
>          self._output_tensor_dict = self._prepare_outputs()
将_prepare_outputs所依赖的self._hook_layers作为参数传进来吧，这样可以方便地看出来init函数中各语句的调用关系和顺序。

2021-09-27 15:40 UTC, wanghaoshuang commented
修改下PR标题，方便以后统计自己的工作。

2021-11-09 06:44 UTC, ceci3 commented on demo/dygraph/dist/bert/task_distill.py
> +        parameters=distill_model.parameters(),
是的

2021-11-09 06:44 UTC, ceci3 commented on demo/dygraph/dist/bert/task_distill.py
> +    assert os.path.exists(
done，thanks

2021-11-09 06:46 UTC, ceci3 commented on paddleslim/dygraph/dist/distill.py
>                   distill_configs,
done, thanks

2021-11-09 06:48 UTC, ceci3 commented on paddleslim/dygraph/dist/distill.py
>          student_models(list(nn.Layer)): the list of student model, the state of student model must be training mode.
这个感觉我们代码里最好不要强行改变用户传入模型的状态，不然可能会导致我们强制改完的和用户想要的不一致

2021-11-09 06:48 UTC, ceci3 commented on paddleslim/dygraph/dist/distill.py
> +        teacher_models(list(nn.Layer)): the list of teacher model.
done, thanks

2021-11-09 06:55 UTC, ceci3 commented on paddleslim/dygraph/dist/distill.py
>          return_model_outputs(bool): whether to return model output. Default: True.
会返回 student 和 teacher 的output.  我把返回格式添加到文件中~

2021-11-09 07:03 UTC, ceci3 commented on paddleslim/dygraph/dist/distill.py
> +                 convert_fn=True,
done,thanks

2021-11-09 07:03 UTC, ceci3 commented on paddleslim/dygraph/dist/distill_helpers.py
> +def paddle_convert_fn():
done, thanks

2021-11-09 12:57 UTC, ceci3 commented on paddleslim/dygraph/dist/distill_helpers.py
> +                setattr(model, 'wrap_fn_{}_{}'.format(fn.__name__, global_idx),
这里不用，调用FuncWrapper class的时候会自动调用 add_sublayer 的

2021-11-09 13:01 UTC, ceci3 commented on paddleslim/dygraph/dist/distill_helpers.py
> +            result = eval('F.before_{}'.format(fn.__name__))(*x, **kwargs)
一个Layer调用多个functional API的话，这些functional 都会被转成class，这里的限制是为了限制以下情况的functional转换：
```python
class ReLU(nn.Layer):
    def __init__(self, name=None):
        super(ReLU, self).__init__()
        self._name = name
    def forward(self, x):
        return F.relu(x, self._name)
```
但是这个限制可能也会有些不严谨，之后也需要改进一下。

2021-11-09 13:02 UTC, ceci3 commented on paddleslim/dygraph/dist/distill_helpers.py
> +class wrapper(nn.Layer):
done, thanks

2021-11-09 13:06 UTC, ceci3 commented on paddleslim/dygraph/dist/distill.py
> +            paddle_convert_fn()
之前写在这里是想到，用户调用转换接口之后拿到layer的名字配置config。然后需要重新启动蒸馏训练，是需要重新调用这个方法对模型进行转换才能拿到匹配的名字，所以就添加了一个自动调用的开关

2021-11-09 13:06 UTC, ceci3 commented on paddleslim/dygraph/dist/distill.py
> +            self._loss_config_list.append(layer_config)
done, thanks

2021-12-04 09:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleSlim?pullRequest=897) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleSlim?pullRequest=897) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ceci3<br/>:x: lvmengsi<br/><hr/>**lvmengsi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleSlim?pullRequest=897) it.</sub>

2021-12-06 03:48 UTC, wanghaoshuang approved these changes

2021-12-06 03:48 UTC, merged