Develop fake data demo
PaddlePaddle/PaddleSlim pull request #943
Opened 2021-12-07 05:39 UTC by lidanqing-intel

To reduce the memory bound for inference on Xeon machines, add fake data demo to better benchmarking the performance.

2022-06-22 16:23 UTC, lidanqing-intel commented
@yeliang2258 Can you please review this PR? If we merge it, we don't have to always clone my repo for benchmarking SPR

2022-06-23 01:52 UTC, lidanqing-intel commented
@jiangjiajun Could you please also approve this PR? Thank you!

2022-06-23 01:59 UTC, yeliang2258 requested changes

2022-06-23 01:59 UTC, yeliang2258 commented on demo/mkldnn_quant/sample_tester_fake_data.cc
> +  for (auto iter = 0; iter<2; iter++){
can use FLAGS_warmup_iter here

2022-06-23 01:59 UTC, yeliang2258 commented on demo/mkldnn_quant/sample_tester.cc
> -DEFINE_int32(warmup_iter, 2, "number of warmup batches");
Why do you need to change it to 1 ?

2022-06-23 02:00 UTC, lidanqing-intel commented on demo/mkldnn_quant/sample_tester_fake_data.cc
> +  for (auto iter = 0; iter<2; iter++){
Ok.

2022-06-23 07:26 UTC, lidanqing-intel commented on demo/mkldnn_quant/sample_tester.cc
> -DEFINE_int32(warmup_iter, 2, "number of warmup batches");
Updated. Please review again. Thanks!

2022-06-23 07:26 UTC, lidanqing-intel commented on demo/mkldnn_quant/sample_tester_fake_data.cc
> +  for (auto iter = 0; iter<2; iter++){
Updated and tested. Please review again. Thanks!

2022-06-23 07:29 UTC, yeliang2258 submitted a review, later dismissed
LGTM

2022-06-23 08:13 UTC, yghstill approved these changes

2022-06-23 12:30 UTC, merged